// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMl2KV88baiF-v9PeY8Gq3z6e6JGGbqI',
    appId: '1:289393054941:web:9b82048cd1b59e76c43734',
    messagingSenderId: '289393054941',
    projectId: 'smart-yoga-met',
    authDomain: 'smart-yoga-met.firebaseapp.com',
    storageBucket: 'smart-yoga-met.firebasestorage.app',
    measurementId: 'G-8B39BLQ6BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4FotsA2tAELw4-o84pKDd0SSxMqq3Lg',
    appId: '1:289393054941:android:6879df2230a808ddc43734',
    messagingSenderId: '289393054941',
    projectId: 'smart-yoga-met',
    storageBucket: 'smart-yoga-met.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuoSvjyd6cD6ZyFY0aWXq2vQBCjs72go',
    appId: '1:289393054941:ios:274e7168a303d746c43734',
    messagingSenderId: '289393054941',
    projectId: 'smart-yoga-met',
    storageBucket: 'smart-yoga-met.firebasestorage.app',
    iosBundleId: 'com.example.smartYogaMat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuoSvjyd6cD6ZyFY0aWXq2vQBCjs72go',
    appId: '1:289393054941:ios:274e7168a303d746c43734',
    messagingSenderId: '289393054941',
    projectId: 'smart-yoga-met',
    storageBucket: 'smart-yoga-met.firebasestorage.app',
    iosBundleId: 'com.example.smartYogaMat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwMl2KV88baiF-v9PeY8Gq3z6e6JGGbqI',
    appId: '1:289393054941:web:e68d04c54ada8975c43734',
    messagingSenderId: '289393054941',
    projectId: 'smart-yoga-met',
    authDomain: 'smart-yoga-met.firebaseapp.com',
    storageBucket: 'smart-yoga-met.firebasestorage.app',
    measurementId: 'G-G8T9XKJPXE',
  );
}
